[theme]
primaryColor = "#00d9ff"
backgroundColor = "#0f1419"
secondaryBackgroundColor = "#1a1f2e"
textColor = "#ffffff"
font = "sans serif"
base = "dark"

[server]
headless = true
port = 8501
maxUploadSize = 200

[browser]
gatherUsageStats = false

